### ISSUE TITLE
How to get mBottomSheetCallback methods to my fragment/activity ?

### ISSUE THREAD

**Issue by avinashbanswada** [laenger/ViewPagerBottomSheet#13]
I am using swipe to refresh view inside bottomsheet viewpager, when I long swipe the view swipe to refresh 
it refresh icon get stuck down as the parent bottom sheet is started moving down, if I know the status of the bottom sheet I clear the swipe to refresh view.

**Comment by laenger** [comment]
maybe i can support when i see a minimal code example/snippet
