### ISSUE TITLE
crash app after update support library:design to 27.0.2

### ISSUE THREAD

**Issue by rasoulinejad** [laenger/ViewPagerBottomSheet#19]
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v4.widget.ViewDragHelper.processTouchEvent(android.view.MotionEvent)' on a null object reference                                                                            at biz.laenger.android.vpbs.ViewPagerBottomSheetBehavior.onTouchEvent(ViewPagerBottomSheetBehavior.java:320)

**Comment by andyken** [comment]
same problem

**Comment by vivekav-96** [comment]
Same issue here

**Comment by crino** [comment]
In [`biz.laenger.android.vpbs.ViewPagerBottomSheetBehavior` line 320](https://github.com/laenger/ViewPagerBottomSheet/blob/36c67312978f21d6a7238e3458543acbcc874125/vpbs/src/main/java/biz/laenger/android/vpbs/ViewPagerBottomSheetBehavior.java#L320) should be
`if (mViewDragHelper != null) {
    mViewDragHelper.processTouchEvent(event);
}`

**Comment by javaghost** [comment]
Or one could add following code [Below this Line:](https://github.com/laenger/ViewPagerBottomSheet/blob/36c67312978f21d6a7238e3458543acbcc874125/vpbs/src/main/java/biz/laenger/android/vpbs/ViewPagerBottomSheetBehavior.java#L319)
```
if (mViewDragHelper == null) {
    mViewDragHelper = ViewDragHelper.create(parent, mDragCallback);
}
```

**Comment by tamhuynhit** [comment]
Same to me :(

**Comment by yamzzzz** [comment]
For now, we can do the following:

```
 bottomSheet.post(new Runnable() {
            @Override
            public void run() {
                bottomSheetBehavior = ViewPagerBottomSheetBehavior.from(bottomSheet);
            }
        });
```

**Comment by laenger** [comment]
just ported the changes from support lib 27.1.0. please let me know if version 0.0.5 solves your issues

**Comment by tamhuynhit** [comment]
It works for me, thanks @laenger
