### ISSUE TITLE
Could not get unknown property

### ISSUE THREAD

**Issue by Rajakrishnanulaganathan** [laenger/ViewPagerBottomSheet#2]
Error:(7, 0) Could not get unknown property 'compileSdkVersion' for root project 'BottomSheetApp' of type org.gradle.api.Project.
<a href="openFile:C:\Users\ADMIN\Downloads\BottomSheetApp\vpbs\build.gradle">Open File</a>

Error:(30, 0) Could not get unknown property 'butterknifeVersion' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
<a href="openFile:C:\Users\ADMIN\Downloads\BottomSheetApp\app\build.gradle">Open File</a>

**Comment by laenger** [comment]
it looks like you copied some configuration from the example app but missed the configuration from the root build.gradle which sets a range of properties:

```
ext {
    ...
    compileSdkVersion = 24
    buildToolsVersion = '24.0.1'
    targetSdkVersion = 24
    supportVersion = '24.2.0'
    butterknifeVersion = '8.2.1'
}
```

alternatively you don't have to use those properties but can just directly set the values in the app build.gradle
