### ISSUE TITLE
Issue in ViewPagerUtils

### ISSUE THREAD

**Issue by saurabhdhillon** [laenger/ViewPagerBottomSheet#22]
`        final int currentItem = viewPager.getCurrentItem();

        for (int i = 0; i < viewPager.getChildCount(); i++) {
            final View child = viewPager.getChildAt(i);
            final ViewPager.LayoutParams layoutParams = (ViewPager.LayoutParams) child.getLayoutParams();
            if (!layoutParams.isDecor && currentItem == layoutParams.position) {
                return child;
            }
        }
        return null;`

layoutParams.position is a private field couldn't use this. Can you help

**Comment by saurabhdhillon** [comment]
@laenger can you help?

**Comment by laenger** [comment]
`ViewPager.LayoutParams.position` is package private which is the reason why [`ViewPagerUtils`](https://github.com/laenger/ViewPagerBottomSheet/blob/master/vpbs/src/main/java/android/support/v4/view/ViewPagerUtils.java) is placed inside `android.support.v4.view` and not `biz.laenger.android.vpbs`
