### ISSUE TITLE
Failed to resolve: biz.laenger.android:vpbs:0.0.5

### ISSUE THREAD

**Issue by sharukhmohammed** [laenger/ViewPagerBottomSheet#28]
I get this error on Studio 3.1 
<img width="900" alt="screen shot 2018-08-20 at 12 16 36" src="https://user-images.githubusercontent.com/3000218/44324322-f34df680-a472-11e8-8bfe-9e0b6e55dc0b.png">

I have added the Maven Url too

**Comment by daniellAlgar** [comment]
Where have you aded the maven repository?

Try to add it to

```
allprojects {
    repositories {
        maven { url "https://raw.github.com/laenger/maven-releases/master/releases" }
    }
}
```

**Comment by sharukhmohammed** [comment]
Now I've moved it to the project level build.gradle file and it syncs without the error.
I wonder why it would fail when it was placed in the module level.
Thanks!

**Comment by sharukhmohammed** [comment]
Why must I mention the maven URL in project level build.gradle? This has drastically improved the build time as it searches for libs like 'play-services' and 'app-compat' in your url. Happens recursively and fails to get anything from the same.

**Comment by laenger** [comment]
`biz.laenger.android:vpbs:0.0.5` is now available in [jcenter](https://bintray.com/laenger/maven-releases/biz.laenger.android%3Avpbs/0.0.5)
