### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by pdavid0** [laenger/ViewPagerBottomSheet#3]
repositories {
    maven { url "https://raw.github.com/laenger/maven-releases/master/releases" }
}

404 not found

**Comment by laenger** [comment]
gradle will use the repository url only as a base and not directly. this link, for example, works just fine:
https://raw.github.com/laenger/maven-releases/master/releases/biz/laenger/android/vpbs/0.0.3/vpbs-0.0.3.aar
