### ISSUE TITLE
Does not handle multiple scrollable children

### ISSUE THREAD

**Issue by SivaramSS** [laenger/ViewPagerBottomSheet#9]
The scroll events are not dispatched when there are adjacent children that can scroll, like scenario below.

```
<LinearLayout
     ...
     layout_behavior="bottom_sheet" >

   <RecyclerView/>
   <NestedScrollView/>
   <ViewPager />

</LinearLayout>
```

**Comment by laenger** [comment]
the original bottom sheet behavior has the same property

**Comment by SivaramSS** [comment]
Yeah, the original bottom sheet behaviour has only one scrollable child object. It would be useful if there was a list of scrollable children.

**Comment by me-abhinav** [comment]
@SivaramSS 
You can wrap your recyclerViews in a single NestedScrollView.

**Comment by hunglv-fs** [comment]
same problem. still not solve

**Comment by laenger** [comment]
no plans to add support here. but seems as if @SivaramSS implemented corresponding changes in his fork
